{
	"version": 1580503177,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiled_of_wall_and_path-sheet0.png",
		"images/tiled_of_wall_and_path-sheet1.png",
		"images/tiled_of_wall_and_path-sheet2.png",
		"images/sponge-sheet0.png",
		"images/sponge-sheet1.png",
		"images/collision_sensors-sheet0.png",
		"images/shadows_and_borders_effect-sheet0.png",
		"images/shadows_and_borders_effect-sheet1.png",
		"images/blue_droplet_particles.png",
		"images/correct_position-sheet0.png",
		"images/level_select_icon-sheet0.png",
		"images/level_select_icon-sheet1.png",
		"images/background-sheet0.png",
		"images/background-sheet1.png",
		"images/button_options-sheet0.png",
		"images/button_levels-sheet0.png",
		"images/yellow_droplet_particles.png",
		"images/level_indicator_text.png",
		"images/level_indicator_board-sheet0.png",
		"images/tiles_background-sheet0.png",
		"images/tiles_background-sheet1.png",
		"images/tiles_background-sheet2.png",
		"images/light_particles-sheet0.png",
		"images/light_particles-sheet1.png",
		"images/light_particles-sheet2.png",
		"images/button_play-sheet0.png",
		"images/button_informations-sheet0.png",
		"images/button_home-sheet0.png",
		"images/puzzle_board-sheet0.png",
		"images/puzzle_board_stem-sheet0.png",
		"images/game_title-sheet0.png",
		"images/decoration_sponge-sheet0.png",
		"images/decoration_sponge-sheet1.png",
		"images/decoration_sponge-sheet2.png",
		"images/level_numbers.png",
		"images/levels_window-sheet0.png",
		"images/select_level_tittle-sheet0.png",
		"images/level_window_indicator-sheet0.png",
		"images/button_right-sheet0.png",
		"images/shadow_creation_sensor-sheet0.png",
		"images/foam_effect-sheet0.png",
		"images/pink_droplet_particles.png",
		"images/green_droplet_particles.png",
		"images/purple_droplet_particles.png",
		"images/red_droplet_particles.png",
		"images/background_overlay-sheet0.png",
		"images/window_options-sheet0.png",
		"images/window_options-sheet1.png",
		"images/window_informations-sheet0.png",
		"images/buton_exit_informations-sheet0.png",
		"images/button_exit_options-sheet0.png",
		"images/button_audio-sheet0.png",
		"images/button_reset_game-sheet0.png",
		"images/loading_bars_background-sheet0.png",
		"images/loading_bar_effect.png",
		"images/loading_progresse_text.png",
		"images/loading_bar_colors-sheet0.png",
		"images/game_version.png",
		"images/button_left-sheet0.png",
		"images/scrol_check-sheet0.png",
		"images/options_title-sheet0.png",
		"images/menu_boards-sheet0.png",
		"images/black_number.png",
		"images/window_game_win-sheet0.png",
		"images/info_game_win-sheet0.png",
		"images/button_next_level-sheet0.png",
		"images/you_win_title-sheet0.png",
		"images/button_restart_level-sheet0.png",
		"images/button_levels2-sheet0.png",
		"images/white_background_number.png",
		"images/light_effect-sheet0.png",
		"images/button_fullscreen-sheet0.png",
		"images/background_overlay_black-sheet0.png",
		"images/help_object-sheet0.png",
		"images/help_object-sheet1.png",
		"images/help_position_sensor-sheet0.png",
		"images/informations_title_background-sheet0.png",
		"images/informations_title-sheet0.png",
		"images/help_info_text-sheet0.png",
		"images/sponge_info_help-sheet0.png",
		"images/sponge_info_help-sheet1.png",
		"media/swip sound effect 1.ogg",
		"media/swip sound effect 2.ogg",
		"media/swip sound effect 3.ogg",
		"media/water sound.ogg",
		"media/button sound.ogg",
		"media/water bubble sound.ogg",
		"media/main music.ogg",
		"media/level completed sound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}