{
	"version": 1578909625,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/btnachievement-sheet0.png",
		"images/btnleaderboard-sheet0.png",
		"images/btnads-sheet0.png",
		"images/btngoogleplay-sheet0.png",
		"images/btnaddsite-sheet0.png",
		"images/btnvideo-sheet0.png",
		"images/btnmoregames-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/btnmusic-sheet0.png",
		"images/btnmusic-sheet1.png",
		"images/btnoption-sheet0.png",
		"images/btnresume-sheet0.png",
		"images/btnhome-sheet0.png",
		"images/btnkiz10-sheet0.png",
		"images/btnmore-sheet0.png",
		"images/btnretry-sheet0.png",
		"images/btnback-sheet0.png",
		"images/btnbuy-sheet0.png",
		"images/btnbuygold-sheet0.png",
		"images/btnnext-sheet0.png",
		"images/btnprev-sheet0.png",
		"images/btnshop-sheet0.png",
		"images/btnshopcoin-sheet0.png",
		"images/btnclose-sheet0.png",
		"images/btnvideoads-sheet0.png",
		"images/btnrocket-sheet0.png",
		"images/btnshoot-sheet0.png",
		"images/bg00-sheet0.png",
		"images/cloud0-sheet0.png",
		"images/cloud1-sheet0.png",
		"images/bg01-sheet0.png",
		"images/bg02-sheet0.png",
		"images/bg10-sheet0.png",
		"images/bg20-sheet0.png",
		"images/ground-sheet0.png",
		"images/bg03-sheet0.png",
		"images/bg11-sheet0.png",
		"images/bg12-sheet0.png",
		"images/bg13-sheet0.png",
		"images/bg21-sheet0.png",
		"images/bg22-sheet0.png",
		"images/bg23-sheet0.png",
		"images/txtgold.png",
		"images/txthighscore.png",
		"images/txtbullet.png",
		"images/bgpreloader-sheet0.png",
		"images/uiloading-sheet0.png",
		"images/fresult-sheet0.png",
		"images/lbest-sheet0.png",
		"images/ldistance-sheet0.png",
		"images/transition-sheet0.png",
		"images/spr1024x450-sheet0.png",
		"images/rotatescreen-sheet0.png",
		"images/cam-sheet0.png",
		"images/notification-sheet0.png",
		"images/uigold-sheet0.png",
		"images/foption-sheet0.png",
		"images/fvideoads-sheet0.png",
		"images/fvideoads-sheet1.png",
		"images/uibullet-sheet0.png",
		"images/game-sheet0.png",
		"images/target-sheet0.png",
		"images/enemybullet-sheet0.png",
		"images/life-sheet0.png",
		"images/vfxflashred-sheet0.png",
		"images/vfxflashwhite-sheet0.png",
		"images/vfxcannonfire-sheet0.png",
		"images/vfxgold-sheet0.png",
		"images/vfxitem-sheet0.png",
		"images/vfxitem-sheet1.png",
		"images/vfxblood0-sheet0.png",
		"images/vfxblood1-sheet0.png",
		"images/vfxexplode-sheet0.png",
		"images/vfxhit-sheet0.png",
		"images/cannonbase-sheet0.png",
		"images/cannon-sheet0.png",
		"images/cannonbar-sheet0.png",
		"images/char0-sheet0.png",
		"images/char0-sheet1.png",
		"images/char-sheet0.png",
		"images/gold-sheet0.png",
		"images/itembullet-sheet0.png",
		"images/trap-sheet0.png",
		"images/enemy0-sheet0.png",
		"images/enemy0-sheet1.png",
		"images/enemy0-sheet2.png",
		"images/enemy1-sheet0.png",
		"images/enemy1-sheet1.png",
		"images/enemy2-sheet0.png",
		"images/enemy3-sheet0.png",
		"images/enemy4-sheet0.png",
		"images/fshopchar-sheet0.png",
		"images/uibuychar-sheet0.png",
		"images/uibuychar-sheet1.png",
		"images/uibuychar-sheet2.png",
		"images/uibuygold-sheet0.png",
		"images/fshopgold-sheet0.png",
		"images/uititle-sheet0.png",
		"images/fupgrade-sheet0.png",
		"images/upgrade0-sheet0.png",
		"images/upgrade1-sheet0.png",
		"images/upgrade2-sheet0.png",
		"images/upgrade3-sheet0.png",
		"images/padlock-sheet0.png",
		"images/ftutorial.png",
		"images/tutorialcannonbase-sheet0.png",
		"images/tutorialcannonbarframe-sheet0.png",
		"images/tutorialbullet-sheet0.png",
		"media/in game.m4a",
		"media/in game.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"media/button prev next.m4a",
		"media/button prev next.ogg",
		"media/button.m4a",
		"media/button.ogg",
		"media/buy.m4a",
		"media/gold.m4a",
		"media/gold.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/not enough gold.m4a",
		"media/not enough gold.ogg",
		"media/power up.m4a",
		"media/power up.ogg",
		"media/select.m4a",
		"media/select.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/buy.ogg",
		"media/cannon shoot.m4a",
		"media/cannon shoot.ogg",
		"media/char bounce.m4a",
		"media/char bounce.ogg",
		"media/char death.m4a",
		"media/char death.ogg",
		"media/char extra life.m4a",
		"media/char extra life.ogg",
		"media/char hit.m4a",
		"media/char hit.ogg",
		"media/char landed.m4a",
		"media/char landed.ogg",
		"media/char rocket.m4a",
		"media/char rocket.ogg",
		"media/char shoot.m4a",
		"media/char shoot.ogg",
		"media/enemy explode.m4a",
		"media/enemy explode.ogg",
		"media/enemy shoot.m4a",
		"media/enemy shoot.ogg",
		"media/shoot.m4a",
		"media/shoot.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}